-- Seed faculty lists for the university onboarding flow.
-- Sources checked in May 2026 from public university faculty pages and admission/faculty directories.

with seed_faculties (institution_name, faculty_name) as (
  values
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Administrație și Afaceri'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Biologie'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Chimie'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Drept'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Filosofie'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Fizică'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Geografie'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Geologie și Geofizică'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Istorie'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Jurnalism și Științele Comunicării'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Limbi și Literaturi Străine'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Litere'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Matematică și Informatică'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Psihologie și Științele Educației'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Sociologie și Asistență Socială'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Științe Politice'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Teologie Baptistă'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Teologie Ortodoxă'),
    ('UNIVERSITATEA DIN BUCUREȘTI', 'Facultatea de Teologie Romano-Catolică'),

    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Inginerie Electrică'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Energetică'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Automatică și Calculatoare'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Electronică, Telecomunicații și Tehnologia Informației'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Inginerie Mecanică și Mecatronică'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Inginerie Industrială și Robotică'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Ingineria Sistemelor Biotehnice'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Transporturi'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Inginerie Aerospațială'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Știința și Ingineria Materialelor'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Inginerie Chimică și Biotehnologii'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Inginerie în Limbi Străine'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Antreprenoriat, Ingineria și Managementul Afacerilor'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Științe Aplicate'),
    ('UNIVERSITATEA NAȚIONALĂ DE ȘTIINȚĂ ȘI TEHNOLOGIE POLITEHNICA BUCUREȘTI', 'Facultatea de Inginerie Medicală'),

    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Administrarea Afacerilor cu predare în limbi străine'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Administrație și Management Public'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Business și Turism'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Cibernetică, Statistică și Informatică Economică'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Contabilitate și Informatică de Gestiune'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Drept'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Economie Agroalimentară și a Mediului'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Economie Teoretică și Aplicată'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Finanțe, Asigurări, Bănci și Burse de Valori'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Management'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Marketing'),
    ('ACADEMIA DE STUDII ECONOMICE DIN BUCUREȘTI', 'Facultatea de Relații Economice Internaționale'),

    ('UNIVERSITATEA DE MEDICINĂ ȘI FARMACIE "CAROL DAVILA" DIN BUCUREȘTI', 'Facultatea de Medicină'),
    ('UNIVERSITATEA DE MEDICINĂ ȘI FARMACIE "CAROL DAVILA" DIN BUCUREȘTI', 'Facultatea de Medicină Dentară'),
    ('UNIVERSITATEA DE MEDICINĂ ȘI FARMACIE "CAROL DAVILA" DIN BUCUREȘTI', 'Facultatea de Farmacie'),
    ('UNIVERSITATEA DE MEDICINĂ ȘI FARMACIE "CAROL DAVILA" DIN BUCUREȘTI', 'Facultatea de Moașe și Asistență Medicală'),

    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Matematică și Informatică'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Fizică'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Chimie și Inginerie Chimică'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Biologie și Geologie'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Geografie'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Știința și Ingineria Mediului'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Drept'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Litere'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Istorie și Filosofie'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Sociologie și Asistență Socială'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Psihologie și Științe ale Educației'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Științe Economice și Gestiunea Afacerilor'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Studii Europene'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Business'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Științe Politice, Administrative și ale Comunicării'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Educație Fizică și Sport'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Teologie Ortodoxă'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Teologie Greco-Catolică'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Teologie Reformată și Muzică'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Teologie Romano-Catolică'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Teatru și Film'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Inginerie'),
    ('UNIVERSITATEA BABEȘ-BOLYAI DIN CLUJ-NAPOCA', 'Facultatea de Științe Medicale și ale Sănătății'),

    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Biologie'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Chimie'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Drept'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Economie și Administrarea Afacerilor'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Educație Fizică și Sport'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Filosofie și Științe Social-Politice'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Fizică'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Geografie și Geologie'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Informatică'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Istorie'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Litere'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Matematică'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Psihologie și Științe ale Educației'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Teologie Ortodoxă'),
    ('UNIVERSITATEA "ALEXANDRU IOAN CUZA" DIN IAȘI', 'Facultatea de Teologie Romano-Catolică'),

    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Arte și Design'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Chimie, Biologie, Geografie'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Drept'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Economie și de Administrare a Afacerilor'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Educație Fizică și Sport'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Fizică și Matematică'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Informatică'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Litere, Istorie și Teologie'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Muzică și Teatru'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Sociologie și Asistență Socială'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Psihologie și Științe ale Educației'),
    ('UNIVERSITATEA DE VEST DIN TIMIȘOARA', 'Facultatea de Științe ale Guvernării și Comunicării'),

    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Arhitectură și Urbanism'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Automatică și Calculatoare'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Construcții'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Electronică, Telecomunicații și Tehnologii Informaționale'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Inginerie Chimică, Biotehnologii și Protecția Mediului'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Inginerie Electrică și Energetică'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Management în Producție și Transporturi'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Mecanică'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Inginerie din Hunedoara'),
    ('UNIVERSITATEA POLITEHNICA TIMIȘOARA', 'Facultatea de Științe ale Comunicării'),

    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Alimentație și Turism'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Construcții'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Design de Mobilier și Inginerie a Lemnului'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Design de Produs și Mediu'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Drept'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Educație Fizică și Sporturi Montane'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Inginerie Electrică și Știința Calculatoarelor'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Inginerie Mecanică'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Inginerie Tehnologică și Management Industrial'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Litere'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Matematică și Informatică'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Medicină'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Muzică'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Psihologie și Științele Educației'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Silvicultură și Exploatări Forestiere'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Sociologie și Comunicare'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Științe Economice și Administrarea Afacerilor'),
    ('UNIVERSITATEA "TRANSILVANIA" DIN BRAȘOV', 'Facultatea de Știința și Ingineria Materialelor'),

    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Arte'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Construcții'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Drept și Științe Administrative'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Educație Fizică și Sport'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Farmacie'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Inginerie Mecanică, Industrială și Maritimă'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Istorie și Științe Politice'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Litere'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Matematică și Informatică'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Medicină'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Stomatologie'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Psihologie și Științele Educației'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Științe Aplicate și Inginerie'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Științe ale Naturii și Științe Agricole'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Științe Economice'),
    ('UNIVERSITATEA "OVIDIUS" DIN CONSTANȚA', 'Facultatea de Teologie'),

    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Agronomie'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Automatică, Calculatoare și Electronică'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Drept'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Economie și Administrarea Afacerilor'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Educație Fizică și Sport'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Horticultură'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Inginerie Electrică'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Litere'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Mecanică'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Științe'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Științe Sociale'),
    ('UNIVERSITATEA DIN CRAIOVA', 'Facultatea de Teologie Ortodoxă'),

    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Arte'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Construcții, Cadastru și Arhitectură'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Drept'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Geografie, Turism și Sport'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Inginerie Electrică și Tehnologia Informației'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Inginerie Energetică și Management Industrial'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Inginerie Managerială și Tehnologică'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Istorie, Relații Internaționale, Științe Politice și Științele Comunicării'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Litere'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Medicină și Farmacie'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Protecția Mediului'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Științe'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Științe Economice'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Științe Socio-Umane'),
    ('UNIVERSITATEA DIN ORADEA', 'Facultatea de Teologie Ortodoxă'),

    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Drept'),
    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Inginerie'),
    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Litere și Arte'),
    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Medicină'),
    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Științe'),
    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Științe Agricole, Industrie Alimentară și Protecția Mediului'),
    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Științe Economice'),
    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Științe Socio-Umane'),
    ('UNIVERSITATEA "LUCIAN BLAGA" DIN SIBIU', 'Facultatea de Teologie'),

    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Arhitectură Navală'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Automatică, Calculatoare, Inginerie Electrică și Electronică'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Drept și Științe Administrative'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Economie și Administrarea Afacerilor'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Educație Fizică și Sport'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Inginerie'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Istorie, Filosofie și Teologie'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Litere'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Medicină și Farmacie'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Știința și Ingineria Alimentelor'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea de Științe și Mediu'),
    ('UNIVERSITATEA "DUNĂREA DE JOS" DIN GALAȚI', 'Facultatea Transfrontalieră'),

    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Drept și Științe Administrative'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Economie, Administrație și Afaceri'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Educație Fizică și Sport'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Inginerie Alimentară'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Inginerie Electrică și Știința Calculatoarelor'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Inginerie Mecanică, Autovehicule și Robotică'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Istorie, Geografie și Științe Sociale'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Litere și Științe ale Comunicării'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Medicină și Științe Biologice'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Silvicultură'),
    ('UNIVERSITATEA "ȘTEFAN CEL MARE" DIN SUCEAVA', 'Facultatea de Științe ale Educației'),

    ('UNIVERSITATEA PETROL-GAZE DIN PLOIEȘTI', 'Facultatea de Ingineria Petrolului și Gazelor'),
    ('UNIVERSITATEA PETROL-GAZE DIN PLOIEȘTI', 'Facultatea de Inginerie Mecanică și Electrică'),
    ('UNIVERSITATEA PETROL-GAZE DIN PLOIEȘTI', 'Facultatea de Tehnologia Petrolului și Petrochimie'),
    ('UNIVERSITATEA PETROL-GAZE DIN PLOIEȘTI', 'Facultatea de Științe Economice'),
    ('UNIVERSITATEA PETROL-GAZE DIN PLOIEȘTI', 'Facultatea de Litere și Științe')
)
insert into public.academic_units (
  institution_id,
  parent_unit_id,
  unit_type,
  name,
  source
)
select
  institutions.id,
  null,
  'faculty',
  seed_faculties.faculty_name,
  'seed'
from seed_faculties
join public.institutions
  on institutions.institution_type = 'university'
  and lower(institutions.name) = lower(seed_faculties.institution_name)
where not exists (
  select 1
  from public.academic_units existing
  where existing.institution_id = institutions.id
    and existing.unit_type = 'faculty'
    and existing.parent_unit_id is null
    and lower(existing.name) = lower(seed_faculties.faculty_name)
);
